name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  melodic_build:
    runs-on:  ubuntu-18.04
    
    container: ros:melodic
    services:
      ros:
        image: ros

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rosdep update
        run: |
          apt-get update
          rosdep update
      - name: Create Workspace
        run: |
          mkdir -p ~/kml_generator/src/
          cp -r `pwd` ~/kml_generator/src/
      - name: Build
        run: |
          cd ~/kml_generator/
          source /opt/ros/melodic/setup.bash
          rosdep install --from-paths src --ignore-src -r -y
          catkin_make -DCMAKE_BUILD_TYPE=Release
